// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    DatePeriod: typeof import('./src/components/DatePeriod.vue')['default']
    Editor: typeof import('./src/components/Editor.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RentForm: typeof import('./src/components/RentForm.vue')['default']
  }
}

export { }
